name: forest
channels:
  - defaults
  - r
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - r-irkernel
  - jupyterlab
  - pandas
  - scikit-learn
  - r
  - r-essentials
  - r-party
  - r-e1071
  - r-mlmetrics
  - pip
  - pip:
        - matplotlib
        - seaborn
